### ISSUE TITLE
App crashed in P3D mode on Nexus 4 Android 4.2.2

### ISSUE THREAD

**Issue by emnullfuenf** [processing/processing-android-archive#40]
When adding P3D in size() even a basic app crashes at start:

Error:
Smooth is not supported by this hardware (or driver)

smooth(); isn't called in the sketch. Adding noSmooth(); to the sketch does not help.

Device:
Nexus 4
Android 4.2.2

Processing 2.0b8

**Comment by boubpopsyteam** [comment]
Duplicate of #3 :)
