### ISSUE TITLE
PVector.set(float float) method does not exist as it should according to documentation and java mode

### ISSUE THREAD

**Issue by smoothmango** [processing/processing-android-archive#47]
In Android mode, the PVector class does not have the same convenience method signature for the set() method.

```
PVector v;
v = new PVector();
v.set(10.0, 20.0);
```

will result in the compile error:

> cannot find symbol
> [javac] symbol  : method set(float,float)
> [javac] location: class processing.core.PVector

This error is not present in java mode, and is rectified in android mode by supplying three floats to the set() method: `set(float, float, float)`
Recommend adding `set(float, float)` for consistency with java mode.

**Comment by boubpopsyteam** [comment]
See https://github.com/processing/processing-android/pull/42 :)

**Comment by shiffman** [comment]
@codeanticode @benfry I think this happened b/c I made some updates to PVector, but I did not realize I needed to update Android mode as well.  Would you like me to make sure they are aligned or does this process happen separately?

**Comment by benfry** [comment]
Now integrated for the next release.
