### ISSUE TITLE
PShape getVertex() not implemented properly for SVG files

### ISSUE THREAD

**Issue by dimkir** [processing/processing-android-archive#49]
Steps to reproduce the error:
1. load any svg
2. get a PShape that has Vertices (printing the Count to the Console works)
3. get any of the Vertices

Expected output: return a PVector
Get instead: ArrayIndexOutOfBoundsException: 2

Originally this bug was filed for desktop version of processing under this issue:
https://github.com/processing/processing/issues/1596

Later it was fixed in _desktop_ version of processing with this commit:
https://github.com/processing/processing/commit/72e2b04245bc85749fcc10d40686bdc8a1ff4a53

This is link to getVertex(int, PVector) method which is errorneous
https://github.com/processing/processing-android/blob/master/core/src/processing/core/PShape.java#L1980

**Comment by codeanticode** [comment]
it has been fixed since this issue was opened.
