### ISSUE TITLE
back button causes app shutdown with no call to keyPressed() or onPause()

### ISSUE THREAD

**Issue by joshgiesbrecht** [processing/processing-android-archive#50]
As per this comment thread of mixed results:
https://forum.processing.org/topic/android-prevent-back-button-from-exiting

And also my own experience using Android 4.0.

Have tried a 'print("KEY PRESSED");' debug line at the top of keyPressed() and it never happens when I press the back button.  What's worse is that onPause() is also never called, meaning the app doesn't get a chance to cleanly save state before exiting.  On normal exiting by pressing the Home button, onPause() is run and works great.

**Comment by benfry** [comment]
Like it says in the Wiki: "The 'back' key works similar to ESC in the desktop version of Processing."
http://wiki.processing.org/w/Android#Mouse.2C_Motion.2C_Keys.2C_and_Input

**Comment by joshgiesbrecht** [comment]
Right, but the wiki also says:

"If you want to do something smarter, override keyPressed() and set 'key' to 0 so that the key doesn't get picked up by the base class."

This doesn't work.

**Comment by joshgiesbrecht** [comment]
Ok, found a fix for my own app.  Had to override nativeKeyEvent(), handleKeyEvent(), and onBackPressed().

I'll try to get a pull request in for this soonish.  There's a bug or two in there, but seems to me like the default behaviour works just fine without any special-case code in nativeKeyEvent() and handleKeyEvent().  So might be easiest and cleanest to just remove it.  Then all you need to customize it is an override of onBackPressed() which seems to be what Android wants you to do these days anyway.

**Comment by joshgiesbrecht** [comment]
Ok, I put in two pull requests.  I really like the onBackPressed() override solution so I submitted it, but since that might mess up people who are expecting or preferring the original usage I also submitted a fix for that.

I'd choose the onBackPressed() version if it were for just me or if the change is not likely to tick anyone off.

**Comment by benfry** [comment]
Thanks, now incorporated.
